
sonar.projectKey=reserva-hotelera-v2
sonar.projectName=StayHub - Reserva Hotelera
sonar.projectVersion=1.1.0
sonar.host.url=http://localhost:9000
sonar.token=sqp_8085e258e209df2f3af0781882e924afc12b8041
sonar.sourceEncoding=UTF-8
sonar.javascript.file.suffixes=.js,.jsx,.ts,.tsx
sonar.sources=frontend/src,backend/src,backend/server.js

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/build/**,\
  **/.env,\
  **/.env.*,\
  **/coverage/**,\
  **/coverage-report/**,\
  backend/src/scripts/setup.js,\
  **/*.min.js,\
  **/*.min.css

sonar.cpd.exclusions=\
  **/node_modules/**,\
  **/dist/**

sonar.security.sources.javasecurity=false
sonar.log.level=INFO
sonar.scanner.socketTimeout=300